# -*- coding: utf-8 -*-
"""google_play_scrape_reviews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKD6Sjzoz3YhScIkKs2eyOBO0uK1o65w

# Google Play Store Review Scraper

This notebook scrapes review text directly from the Google Play Store using the `google-play-scraper` package.

It is set up for:
- one or many app IDs
- review pagination
- de-duplication by `review_id`
- CSV export
- metadata export
- a quick validation summary after scraping

## 1) Install dependencies

Run this cell once if the environment does not already have the required packages.
"""

# Uncomment if needed
!pip install -q google-play-scraper

"""## 2) Imports"""

import json
import time
from pathlib import Path

import pandas as pd
from google_play_scraper import Sort, reviews

"""## 3) Scrape settings

Update the app IDs and collection settings here.

Notes:
- `lang='en'` and `country='us'` keeps the collection focused and easier to compare.
- `sort='NEWEST'` is usually the best first pass for recent product feedback.
- Google Play paging is typically capped at 200 reviews per request.
"""

APP_IDS = [
    "com.spotify.music",
    "com.instagram.android",
    "com.zhiliaoapp.musically",
    "com.snapchat.android",
    "com.whatsapp",
]

LANG = "en"
COUNTRY = "us"
SORT_NAME = "NEWEST"   # options: NEWEST, HELPFULNESS, RATING
COUNT_PER_APP = 6000      # target reviews to request per app
MAX_REVIEWS = 30000      # stop once this many unique reviews are collected total
BATCH_SIZE = 200         # per-request page size
SLEEP_SECONDS = 0.5      # small pause to reduce throttling risk

OUT_CSV = "google_play_reviews.csv"
OUT_METADATA = "google_play_reviews_run_metadata.json"

"""## 4) Helpers"""

SORT_MAP = {
    "NEWEST": Sort.NEWEST,
    "RATING": Sort.RATING,
    "HELPFULNESS": getattr(Sort, "MOST_RELEVANT", getattr(Sort, "HELPFULNESS", Sort.NEWEST)),
}


def normalize_review(raw, app_id, lang, country):
    content = raw.get("content") or raw.get("text") or ""
    at = raw.get("at") or raw.get("date")
    reply_content = raw.get("replyContent") or raw.get("replyText")
    reply_at = raw.get("repliedAt") or raw.get("replyDate")

    return {
        "app_id": app_id,
        "review_id": raw.get("reviewId") or raw.get("id"),
        "user_name": raw.get("userName"),
        "score": raw.get("score"),
        "review_text": content,
        "thumbs_up": raw.get("thumbsUpCount", raw.get("thumbsUp")),
        "review_created_at": at.isoformat() if hasattr(at, "isoformat") else at,
        "app_version": raw.get("reviewCreatedVersion", raw.get("version")),
        "reply_text": reply_content,
        "reply_created_at": reply_at.isoformat() if hasattr(reply_at, "isoformat") else reply_at,
        "lang": lang,
        "country": country,
    }


def scrape_one_app(
    app_id,
    lang,
    country,
    sort_name,
    count_per_app,
    batch_size,
    sleep_seconds,
    seen_review_ids,
    max_reviews_remaining,
):
    collected = []
    continuation_token = None
    requested = 0
    sort_enum = SORT_MAP[sort_name]

    while requested < count_per_app and len(collected) < max_reviews_remaining:
        this_batch = min(batch_size, count_per_app - requested, max_reviews_remaining - len(collected))

        result, continuation_token = reviews(
            app_id,
            lang=lang,
            country=country,
            sort=sort_enum,
            count=this_batch,
            continuation_token=continuation_token,
        )

        if not result:
            break

        batch_new = 0
        for raw in result:
            review_id = raw.get("reviewId") or raw.get("id")
            if review_id and review_id in seen_review_ids:
                continue
            if review_id:
                seen_review_ids.add(review_id)

            collected.append(normalize_review(raw, app_id, lang, country))
            batch_new += 1

            if len(collected) >= max_reviews_remaining:
                break

        requested += this_batch

        if continuation_token is None or batch_new == 0:
            break

        if sleep_seconds > 0:
            time.sleep(sleep_seconds)

    return collected

"""## 5) Run the scrape

This cell iterates through the app basket, collects reviews, saves a CSV, and writes run metadata.
"""

all_rows = []
seen_review_ids = set()
per_app_counts = {}
errors = {}

for app_id in APP_IDS:
    remaining = MAX_REVIEWS - len(all_rows)
    if remaining <= 0:
        break

    try:
        rows = scrape_one_app(
            app_id=app_id,
            lang=LANG,
            country=COUNTRY,
            sort_name=SORT_NAME,
            count_per_app=COUNT_PER_APP,
            batch_size=BATCH_SIZE,
            sleep_seconds=SLEEP_SECONDS,
            seen_review_ids=seen_review_ids,
            max_reviews_remaining=remaining,
        )
        all_rows.extend(rows)
        per_app_counts[app_id] = len(rows)
        print(f"{app_id}: collected {len(rows)} unique reviews")
    except Exception as exc:
        errors[app_id] = str(exc)
        print(f"{app_id}: error: {exc}")

df = pd.DataFrame(all_rows)
df.to_csv(OUT_CSV, index=False)

metadata = {
    "total_unique_reviews": len(df),
    "app_count_attempted": len(APP_IDS),
    "app_count_succeeded": len(per_app_counts),
    "per_app_counts": per_app_counts,
    "errors": errors,
    "lang": LANG,
    "country": COUNTRY,
    "sort": SORT_NAME,
    "count_per_app": COUNT_PER_APP,
    "max_reviews": MAX_REVIEWS,
    "output_csv": str(Path(OUT_CSV).resolve()),
}

Path(OUT_METADATA).write_text(json.dumps(metadata, indent=2), encoding="utf-8")

print(json.dumps(metadata, indent=2))

"""## 6) Quick validation

Use this to verify that the scrape worked and inspect the shape of the output.
"""

df.head()

print("Rows:", len(df))
print("Apps:", df['app_id'].nunique() if not df.empty else 0)
print("Missing review text:", int(df['review_text'].isna().sum()) if 'review_text' in df.columns else 0)
print("Duplicate review_id:", int(df['review_id'].duplicated().sum()) if 'review_id' in df.columns else 0)

if not df.empty and 'score' in df.columns:
    print("Rating distribution:")
    print(df['score'].value_counts(dropna=False).sort_index())

"""## 7) Optional: save a cleaned version

This is just a light first-pass cleaning example.
"""

if not df.empty:
    clean_df = df.copy()
    clean_df = clean_df.drop_duplicates(subset=['review_id'])
    clean_df['review_text'] = clean_df['review_text'].fillna('').astype(str).str.strip()
    clean_df = clean_df[clean_df['review_text'] != '']
    clean_df = clean_df[clean_df['score'].isin([1, 2, 3, 4, 5])]

    clean_out = "google_play_reviews_clean.csv"
    clean_df.to_csv(clean_out, index=False)
    print(f"Saved cleaned file to {Path(clean_out).resolve()}")
    print("Clean rows:", len(clean_df))
else:
    print("No rows collected yet.")